name: init

inputs:
  BOT_GITHUB_PAT:
    description: "Bot GitHub PAT"
    required: true
  GO_VERSION:
    description: "Go Version"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.GO_VERSION }}

    - name: Configure Git
      run: git config --global url."https://${{ inputs.BOT_GITHUB_PAT }}@github.com/".insteadOf "https://github.com/"
      shell: sh

    - name: Download Go Modules
      run: go mod download
      shell: sh
